// Character definitions - each character comes from a different asset pack
// frameW/frameH: sprite frame dimensions (null = use whole image as single frame)
export const CHARACTERS = [
  {
    id: 'cute',
    name: 'Cute Hero',
    pack: 'Cute_Fantasy_Free',
    sprite: 'Player/Player.png',
    frameW: 32, frameH: 64,
    cols: 6, rows: 5,
    scale: 1.5,
    speed: 180, jump: 420, attack: 1,
    anims: { idle: [0, 3], run: [4, 7], jump: [8, 9], attack: [10, 13], hurt: [14, 15] },
    desc: 'A brave farmer from Sunnyside. Balanced stats.',
  },
  {
    id: 'caverman',
    name: 'Caverman',
    pack: 'prehistoric-platformer',
    sprite: 'characters/playable/caverman.png',
    frameW: 64, frameH: 64,
    cols: 9, rows: 8,
    scale: 1.2,
    speed: 200, jump: 460, attack: 1,
    anims: { idle: [0, 3], run: [4, 7], jump: [8, 9], attack: [10, 13], hurt: [14, 15] },
    desc: 'A prehistoric powerhouse. High jump, strong attack.',
  },
  {
    id: 'ninja',
    name: 'Ninja',
    pack: 'ninja-adventure',
    sprite: 'characters/1.png',
    frameW: 32, frameH: 56,
    cols: 2, rows: 2,
    scale: 1.5,
    speed: 240, jump: 440, attack: 1,
    anims: { idle: [0, 1], run: [2, 3], jump: [1, 1], attack: [2, 3], hurt: [0, 0] },
    desc: 'Swift and silent. Fastest runner in the rift.',
  },
  {
    id: 'cowboy',
    name: 'Cowboy',
    pack: 'western-fps-2d',
    sprite: 'characters/15.png',
    frameW: 36, frameH: 50,
    cols: 1, rows: 1,
    scale: 1.5,
    speed: 190, jump: 400, attack: 2,
    anims: { idle: [0, 0], run: [0, 0], jump: [0, 0], attack: [0, 0], hurt: [0, 0] },
    desc: 'A gunslinger with a quick draw. Strongest attack.',
  },
  {
    id: 'ship',
    name: 'Star Ship',
    pack: 'space-shooter',
    sprite: 'ships/1.png',
    frameW: 63, frameH: 51,
    cols: 1, rows: 1,
    scale: 1.2,
    speed: 260, jump: 500, attack: 1,
    anims: { idle: [0, 0], run: [0, 0], jump: [0, 0], attack: [0, 0], hurt: [0, 0] },
    desc: 'A rift-traveling starship. Fast and agile.',
  },
  {
    id: 'farmer',
    name: 'Mana Farmer',
    pack: 'Mana Seed Farmer Sprite Free Sample',
    sprite: 'farmer base sheets/01body/fbas_1body_human_00.png',
    frameW: 64, frameH: 64,
    cols: 16, rows: 16,
    scale: 1.0,
    speed: 170, jump: 380, attack: 1,
    anims: { idle: [0, 3], run: [4, 7], jump: [8, 9], attack: [10, 13], hurt: [14, 15] },
    desc: 'A mystical farmer touched by mana. Balanced stats.',
  },
];

export function getCharacter(id) {
  return CHARACTERS.find(c => c.id === id) || CHARACTERS[0];
}
